### ISSUE TITLE
Unable to load Plugin.cs (Godot 4.3 Dev)

### ISSUE THREAD

**Issue by RyixDevelopment** [spimort/TerraBrush#88]
I have godot 4.3dev5 .NET version installed. i reinstalled the plugin, but it keeps giving me: 

"Unable to load addon script from path: 'res://addons/terrabrush/Plugin.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/terrabrush/plugin.cfg' to prevent further errors."

**Comment by MatthewBlanchard** [comment]
Same here.

**Comment by Schwagsone** [comment]
Heard there was an issue with 4.3 and he's looking at a fix.

**Comment by spimort** [comment]
As for now the plugin is compatible with the stable 4.x version of Godot but I'll check to make it work with 4.3 as well 🙂.

**Comment by HEofOttoman** [comment]
same issue here
spams errors when i try to build

**Comment by spimort** [comment]
I've done some test this week with the latest 4.3 version and it seems to have an issue with the dock I'm trying to add. Not quite sure yet if this is something I can fix or it's in godot directly.

4.3 is still unstable so maybe something is broken with plugin support.

I'll have to do more testing.

**Comment by HEofOttoman** [comment]
Oh wait my version of Godot is 4.2

**Comment by spimort** [comment]
> Oh never mind my version of Godot is 4.2

In this case, it should work perfectly.
Make sure you run Godot .net and that you have dotnet sdk installed.
Then, make sure you hit the hammer button next to the play button 🙂

**Comment by HEofOttoman** [comment]
[msbuild_log.txt](https://github.com/spimort/TerraBrush/files/15282193/msbuild_log.txt)
I am unable to build, this happened.

**Comment by spimort** [comment]
> [msbuild_log.txt](https://github.com/spimort/TerraBrush/files/15282193/msbuild_log.txt) I am unable to build, this happened. I am sorry if this is a common mistake

If you look at the errors, it seems like you have twice the addon, in your files : 
![image](https://github.com/spimort/TerraBrush/assets/6035485/a9202383-45c7-444b-af24-10edbbd9798f)

**Comment by HEofOttoman** [comment]
oh i see. The problem is fixed thank you

**Comment by spimort** [comment]
I started to look at the issues for 4.3 and damn, it feels like the docking system (when I add the panels with the tools) is kinda broken. I've been able to fix most of it so far, but now I have an issue with the water 😭.

They changed how they use the DEPTH_TEXTURE and I use it in the water shader.

https://godotengine.org/article/introducing-reverse-z/

Godot 4.3 is still not released yet, so maybe I'll have to wait for the official release, so I don't have to support both DEPTH_TEXTURE way to work.

Anyway, it was just an update on the situation.

**Comment by spimort** [comment]
@RyixDevelopment Godot 4.3 Beta 1 is out. I did a quick Test with TerraBrush and it seems fine with this version (a part from the water that I'll have to do something when it releases) 🙂.

I don't know if you want to try it with it or not?
Let me know if you do. 
I'll close the issue after the tests (or in a few days).

**Comment by spimort** [comment]
I'll close the issue for now, feel free to reopen one if you still have issues with this.
